version: '3.4'

services:
  profio.api-1:
    image: ${DOCKER_REGISTRY-}profioapi
    container_name: profio-api-1
    build:
      context: .
      dockerfile: apps\Profio.Api\Dockerfile
  profio.api-2:
    image: ${DOCKER_REGISTRY-}profioapi
    container_name: profio-api-2
    build:
      context: .
      dockerfile: apps\Profio.Api\Dockerfile
  profio.api-3:
    image: ${DOCKER_REGISTRY-}profioapi
    container_name: profio-api-3
    build:
      context: .
      dockerfile: apps\Profio.Api\Dockerfile
